### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dgirona** [Arageek/option-tree#1]
Notice: Only variables should be passed by reference in /homepages/30/d419872697/htdocs/makeupvictim
/wp-content/themes/enspire-master/option-tree/ot-loader.php on line 329

Any idea please?

http://makeupvictim.com

**Comment by nash-ye** [comment]
It's already fixed in this fork, Are you using it?

**Comment by dgirona** [comment]
I do not see where the solution is. Sorry

**Comment by nash-ye** [comment]
it's fixed [here](https://github.com/Arageek/option-tree/commit/4c1bd1097a4dc2a25dfa88c48b79472d02869f31).

[Download](https://github.com/Arageek/option-tree/archive/master.zip) the current version and replace the option-tree copy in your theme.

**Comment by dgirona** [comment]
Thanks : )
